// Send a generated scribe document via Resend
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function htmlEscape(s: string) {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { recipientEmail, subject, documentText, patientName } = await req.json();
    if (!recipientEmail || !documentText) throw new Error("recipientEmail and documentText required");

    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY not configured");

    const safeBody = htmlEscape(documentText).replace(/\n/g, "<br/>");
    const html = `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#0f172a;background:#fff;padding:24px">
      <h2 style="color:#1d4ed8">Medical Scribe — ${htmlEscape(patientName || "")}</h2>
      <div style="white-space:normal;line-height:1.5;font-size:14px">${safeBody}</div>
      <hr/><p style="font-size:12px;color:#64748b">Generated by Medical Scribe Generator.</p>
    </body></html>`;

    const resp = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: "Medical Scribe <onboarding@resend.dev>",
        to: [recipientEmail],
        subject: subject || `Medical Scribe — ${patientName || ""}`,
        html,
      }),
    });

    const data = await resp.json();
    if (!resp.ok) {
      console.error("Resend error", resp.status, data);
      return new Response(JSON.stringify({ error: data?.message || "Failed to send email" }), {
        status: resp.status,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    return new Response(JSON.stringify({ ok: true, id: data?.id }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error(e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
